//! Gateway message types for channel-based communication.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

use crate::types::SessionKey;

/// Provenance of an inbound message: who put it on the bus.
///
/// Content-triggered automation (e.g. forced background workflows) must only
/// fire on `ExternalUser` traffic. `Synthetic` marks messages the runtime
/// writes to itself — child-completion notices, continuation prompts,
/// recovery turns. Running keyword detection on those is a feedback loop by
/// construction: a completion notice embeds its workflow's own label, so it
/// re-triggers the workflow it reports on (#1455).
///
/// Serde-defaults to `ExternalUser` so pre-existing serialized messages
/// (which are all channel traffic) keep their behavior; synthetic producers
/// construct in-process and never rely on the default.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum MessageOrigin {
    /// Sent by a human (or user-controlled client) through a channel adapter,
    /// or user-authored content replayed on the user's behalf (e.g. cron
    /// payloads).
    #[default]
    ExternalUser,
    /// Generated by the runtime itself and re-injected into the session
    /// inbox (supervision notices, heartbeats, recovery prompts).
    Synthetic,
}

/// Inbound message from a channel to the agent.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InboundMessage {
    pub channel: String,
    pub sender_id: String,
    pub chat_id: String,
    pub content: String,
    pub timestamp: DateTime<Utc>,
    #[serde(default)]
    pub media: Vec<String>,
    #[serde(default = "default_metadata")]
    pub metadata: serde_json::Value,
    /// Platform message ID (e.g. Telegram msg.id) for threading replies.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub message_id: Option<String>,
    /// Provenance gate for content-triggered automation (#1455).
    #[serde(default)]
    pub origin: MessageOrigin,
}

/// Outbound message from the agent to a channel.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OutboundMessage {
    pub channel: String,
    pub chat_id: String,
    pub content: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reply_to: Option<String>,
    #[serde(default)]
    pub media: Vec<String>,
    #[serde(default = "default_metadata")]
    pub metadata: serde_json::Value,
}

fn default_metadata() -> serde_json::Value {
    serde_json::Value::Object(serde_json::Map::new())
}

impl InboundMessage {
    pub fn session_key(&self) -> SessionKey {
        SessionKey::new(&self.channel, &self.chat_id)
    }

    /// True when this message came from outside the runtime (channel user
    /// traffic). Content-triggered automation must check this before acting
    /// on message text (#1455).
    pub fn is_external_user(&self) -> bool {
        self.origin == MessageOrigin::ExternalUser
    }
}

/// Metadata key for the Matrix sender user ID (appservice identity assertion).
///
/// Set by the outbound forwarder when a profile has a dedicated bot user;
/// consumed by `MatrixChannel::send_with_id()` for appservice identity assertion.
pub const METADATA_SENDER_USER_ID: &str = "sender_user_id";

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_inbound_session_key() {
        let msg = InboundMessage {
            channel: "telegram".into(),
            sender_id: "user1".into(),
            chat_id: "chat42".into(),
            content: "hello".into(),
            timestamp: Utc::now(),
            media: vec![],
            metadata: serde_json::json!({}),
            message_id: None,
            origin: MessageOrigin::ExternalUser,
        };
        assert_eq!(msg.session_key(), SessionKey::new("telegram", "chat42"));
    }

    #[test]
    fn test_inbound_serde_roundtrip() {
        let msg = InboundMessage {
            channel: "cli".into(),
            sender_id: "local".into(),
            chat_id: "default".into(),
            content: "test message".into(),
            timestamp: Utc::now(),
            media: vec!["image.png".into()],
            metadata: serde_json::json!({"key": "value"}),
            message_id: None,
            origin: MessageOrigin::ExternalUser,
        };
        let json = serde_json::to_string(&msg).unwrap();
        let parsed: InboundMessage = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.content, "test message");
        assert_eq!(parsed.media.len(), 1);
    }

    #[test]
    fn test_outbound_serde_roundtrip() {
        let msg = OutboundMessage {
            channel: "cli".into(),
            chat_id: "default".into(),
            content: "response".into(),
            reply_to: Some("msg-1".into()),
            media: vec![],
            metadata: serde_json::json!({}),
        };
        let json = serde_json::to_string(&msg).unwrap();
        let parsed: OutboundMessage = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.content, "response");
        assert_eq!(parsed.reply_to, Some("msg-1".into()));
    }

    #[test]
    fn test_inbound_default_metadata() {
        let json = r#"{
            "channel": "cli",
            "sender_id": "local",
            "chat_id": "default",
            "content": "hi",
            "timestamp": "2024-01-01T00:00:00Z"
        }"#;
        let msg: InboundMessage = serde_json::from_str(json).unwrap();
        assert_eq!(msg.media.len(), 0);
        assert!(msg.metadata.is_object());
    }

    #[test]
    fn should_default_origin_to_external_user_when_field_absent() {
        // Pre-#1455 serialized messages (all channel traffic) carry no
        // origin field; they must keep external-user behavior.
        let json = r#"{
            "channel": "telegram",
            "sender_id": "u1",
            "chat_id": "c1",
            "content": "hi",
            "timestamp": "2024-01-01T00:00:00Z"
        }"#;
        let msg: InboundMessage = serde_json::from_str(json).unwrap();
        assert_eq!(msg.origin, MessageOrigin::ExternalUser);
        assert!(msg.is_external_user());
        let synthetic = InboundMessage {
            origin: MessageOrigin::Synthetic,
            ..msg
        };
        assert!(!synthetic.is_external_user());
        let roundtrip: InboundMessage =
            serde_json::from_str(&serde_json::to_string(&synthetic).unwrap()).unwrap();
        assert_eq!(roundtrip.origin, MessageOrigin::Synthetic);
    }
}
